package web

// Code generated by ./errors_gen.sh; DO NOT EDIT

//go:generate ./errors_gen.sh

import (
	"fmt"
	"net/http"

	"darvaza.org/x/fs"
)

// NewStatusMovedPermanently returns a 301 redirect error.
func NewStatusMovedPermanently(dest string, args ...any) *HTTPError {
	if len(args) > 0 {
		dest = fmt.Sprintf(dest, args...)
	}

	dest, _ = fs.Clean(dest)

	return &HTTPError{
		Code: http.StatusMovedPermanently,
		Hdr: http.Header{
			"Location": []string{dest},
		},
	}
}

// NewStatusFound returns a 302 redirect error.
func NewStatusFound(dest string, args ...any) *HTTPError {
	if len(args) > 0 {
		dest = fmt.Sprintf(dest, args...)
	}

	dest, _ = fs.Clean(dest)

	return &HTTPError{
		Code: http.StatusFound,
		Hdr: http.Header{
			"Location": []string{dest},
		},
	}
}

// NewStatusSeeOther returns a 303 redirect error.
func NewStatusSeeOther(dest string, args ...any) *HTTPError {
	if len(args) > 0 {
		dest = fmt.Sprintf(dest, args...)
	}

	dest, _ = fs.Clean(dest)

	return &HTTPError{
		Code: http.StatusSeeOther,
		Hdr: http.Header{
			"Location": []string{dest},
		},
	}
}

// NewStatusTemporaryRedirect returns a 307 redirect error.
func NewStatusTemporaryRedirect(dest string, args ...any) *HTTPError {
	if len(args) > 0 {
		dest = fmt.Sprintf(dest, args...)
	}

	dest, _ = fs.Clean(dest)

	return &HTTPError{
		Code: http.StatusTemporaryRedirect,
		Hdr: http.Header{
			"Location": []string{dest},
		},
	}
}

// NewStatusPermanentRedirect returns a 308 redirect error.
func NewStatusPermanentRedirect(dest string, args ...any) *HTTPError {
	if len(args) > 0 {
		dest = fmt.Sprintf(dest, args...)
	}

	dest, _ = fs.Clean(dest)

	return &HTTPError{
		Code: http.StatusPermanentRedirect,
		Hdr: http.Header{
			"Location": []string{dest},
		},
	}
}

// NewStatusNotModified returns a 304 HTTP error.
func NewStatusNotModified() *HTTPError {
	return &HTTPError{
		Code: http.StatusNotModified,
	}
}
