#!/bin/sh

set -eu

TAG=go:generate
GOFILE=${GOFILE:-$0.go}
GOPACKAGE=${GOPACKAGE:-web}

exec > "$GOFILE~"

cat <<EOT
package $GOPACKAGE

// Code generated by $0; DO NOT EDIT

//$TAG $0

import (
	"fmt"
	"net/http"

	"darvaza.org/x/fs"
)
EOT

# redirects
#
for x in \
	MovedPermanently=301 \
	Found=302 \
	SeeOther=303 \
	TemporaryRedirect=307 \
	PermanentRedirect=308 \
	; do

	name=${x%=*}
	code=${x#*=}

	cat <<EOT

// NewStatus$name returns a $code redirect error.
func NewStatus$name(dest string, args ...any) *HTTPError {
	if len(args) > 0 {
		dest = fmt.Sprintf(dest, args...)
	}

	dest, _ = fs.Clean(dest)

	return &HTTPError{
		Code: http.Status$name,
		Hdr: http.Header{
			"Location": []string{dest},
		},
	}
}
EOT
done

# basic
#
for x in \
	NotModified=304 \
	; do

	name=${x%=*}
	code=${x#*=}

	cat <<EOT

// NewStatus$name returns a $code HTTP error.
func NewStatus$name() *HTTPError {
	return &HTTPError{
		Code: http.Status$name,
	}
}
EOT
done

mv "$GOFILE~" "$GOFILE"
